name: Rust

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: cache cargo setup
      id: cache-cargo-setup
      uses: actions/cache@v2
      with:
        path: |
         ~/.cargo/registry
         ~/.cargo/bin
         ~/.cargo/git
           target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: cargo setup
      if: steps.cache-cargo-setup.cache-hit != 'true'
      run: test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update && test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook && cargo install-update -a
    
    - name: build book
      run: ./genbook.sh
      shell: bash

    - name: push github
      run: git config --global user.email "daedalus.2713@gmail.com" && git config --global user.name "daedalus2713" && git config --global url."https://daedalus2713:${{ secrets.SECRET_NAME }}@github.com".insteadOf "https://github.com" && git add . && git commit --allow-empty -m "build book" && git show-ref && git push origin HEAD:master
