name: Rust

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: cache cargo setup
      id: cache-cargo-setup
      uses: actions/cache@v2
      with:
        path: |
         ~/.cargo/registry
         ~/.cargo/bin
         ~/.cargo/git
           target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: push github
      run: git config --global user.email "daedalus.2713@gmail.com" && git config --global user.name "daedalus2713" && git config --global url."https://daedalus2713:${{ secrets.SECRET_NAME }}@github.com".insteadOf "https://github.com" && git add . && git commit --allow-empty -m "build book" && git push origin HEAD:master
